name: coverage

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [dev]

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  analyse:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_APP=OFF -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
        env:
          CC: gcc
          CXX: g++

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Test, get coverage reports and run sanitizers
        working-directory: ${{github.workspace}}/build
        run: ctest -C${{env.BUILD_TYPE}}

      - name: Upload coverage reports to CodeCov
        working-directory: ${{github.workspace}}/build
        run: bash <(curl -s https://codecov.io/bash)
