name: sanitizer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  sanitize:
    name: Sanitizer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install GMP and MPFR
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install libgmp-dev libmpfr-dev

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dfintamath_build_tests=ON -Dfintamath_enable_sanitizers=ON
        env:
          CC: gcc
          CXX: g++

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
